name: Docker Image CI

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Harbor
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get the date and time
        run: echo "BUILD_DATETIME=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build and push Docker Image
        run: |
          docker build . --file Dockerfile \
            --tag ${{ secrets.REGISTRY_URL }}/sandbox/pepup:${{ env.BUILD_DATETIME }} \
            --build-arg MYSQL_URL=${{ secrets.MYSQL_URL }} \
            --build-arg PG_DATABASE_URL=${{ secrets.PG_DATABASE_URL }}
          docker push ${{ secrets.REGISTRY_URL }}/sandbox/pepup:${{ env.BUILD_DATETIME }}

      - name: Update manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.REGISTRY_URL }}/sandbox/pepup:${{ env.BUILD_DATETIME }}|" manifest/manifest.yaml

      - name: Commit and push manifest
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add manifest/manifest.yaml
          git commit -m "Update manifest to ${{ env.BUILD_DATETIME }}"
          git push
